### ISSUE TITLE
problems with cucumber 3

### ISSUE THREAD

**Issue by seymen** [vgamula/gulp-cucumber#42] opened 2017-08-16 20:32 UTC
Hi there,

I am using cucumber-js 3 and having problems running cucumber tests with gulp-cucumber. Same feature files are working with cucumber-js but failing with gulp-cucumber.

Here is the error I am getting:
```
[21:29:02] Starting 'cucumber'...
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1254:5)
    at getDefinitionLineAndUri (/Users/ooo/projects/poc/gulp-cucumber-test/node_modules/cucumber/lib/support_code_library_builder/define_helpers.js:144:28)
    at /Users/ooo/projects/poc/gulp-cucumber-test/node_modules/cucumber/lib/support_code_library_builder/define_helpers.js:108:34
    at /Users/ooo/projects/poc/gulp-cucumber-test/features/step_definitions/browser_steps.js:5:3
    at defineSupportCode (/Users/ooo/projects/poc/gulp-cucumber-test/node_modules/cucumber/lib/support_code_library_builder/index.js:43:9)
    at Object.<anonymous> (/Users/ooo/projects/poc/gulp-cucumber-test/features/step_definitions/browser_steps.js:4:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /Users/ooo/projects/poc/gulp-cucumber-test/node_modules/gulp-cucumber/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:63:29
    at Array.forEach (<anonymous>)
```

Any ideas or workarounds?
Cheers

**Comment by seymen** [comment] 2017-08-16 21:21
I am also getting the same error when copying/pasting code in cucumber's node.js example in an empty project: https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md

**Comment by pmosconi** [comment] 2017-08-23 12:34
I am having the same problem and I believe it is caused by gulp-cucumber having an internal dependency on cucumber@1.2.1: the order of module.paths makes this one loaded instead of cucumber@3 when cucumber is required.
Running  ./node_modules/.bin/cucumber-js from command line executes cucumber@3.

I am using apickli too, and I have encountered at least another error when upgrading to V2, but here  that's out of scope.

**Comment by u9520107** [comment] 2017-08-24 00:28
@pmosconi I've made a PR #43 to base gulp-cucumber on cucumber@3. I've also made cucumber a peer dependency. Hopefully that's sufficient to solve your problems.

**Comment by vgamula** [comment] 2017-08-25 08:14
Hey, sorry for being so late.

@seymen @pmosconi #43 is merged, I bumped new version v0.0.23, which contains all @u9520107 
 fixes, you can try it now. If something works wrong - please, feel free to ping me, I will try to help you.

Thank you!

**Closed** 2017-08-25 08:14 UTC

**Comment by seymen** [comment] 2017-08-25 15:23
👍  v0.0.23 is working for me now. Cheers.

**Comment by stupiduglyfool** [comment] 2017-08-29 11:51
Package 0.0.23 now does not work with older cucumber versions, with a very similar error to above.

Since you've upgraded a dependency to a new major version, shouldn't your new version number be at least 0.1.23?
